model:
  N: 256
  M: 192

data:
  root_dir: data/processed/kitti
  transforms:
    resize:
      enabled: false
      size: [384, 1280]
    crop:
      enabled: false
      size: 256
    horizontal_flip:
      enabled: true
      probability: 0.5
    color_jitter:
      enabled: true
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.05
    normalize:
      enabled: false
  
  # Transform configuration for VAL/TEST (identity)
  test_transforms:
    resize: { enabled: false, size: [384, 1280] }
    crop: { enabled: false, size: 256 }
    horizontal_flip: { enabled: false, probability: 0.5 }
    color_jitter: { enabled: false, brightness: 0.2, contrast: 0.2, saturation: 0.2, hue: 0.05 }
    normalize: { enabled: false, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225] }

training:
  save_dir: checkpoints/lmsfc_anchor
  batch_size: 8
  num_workers: 8
  learning_rate: 1.0e-4
  epochs: 100
  lambda: 20
  log_interval: 50
  lr_schedule:
    enabled: true
    factor: 0.5
    patience: 5
    min_lr: 1.0e-6
  early_stopping:
    enabled: true
    patience: 5
    min_delta: 1.0e-4  # Minimum change in validation loss to qualify as an improvement
