# Configuration for training factorized prior FPN feature compression model

model:
  n_hidden: 128           # Number of hidden channels in the encoder/decoder
  n_channels: 192         # Number of channels in the latent representation
  fpn_channels_per_level: 256  # Number of channels per FPN level (standard for ResNet50 FPN)
  num_fpn_levels: 5       # Number of FPN levels (P2, P3, P4, P5, P6)

# Detection model configuration for FPN feature extraction
# Note: num_classes is automatically determined from KITTIDetectionDataset.CLASSES + 1 (background)

data:
  # Dataset paths
  train_list: 'data/processed/kitti/train.txt'
  val_list: 'data/processed/kitti/val.txt'
  
  # Image preprocessing for FPN feature extraction
  # Note: These transforms are applied to INPUT IMAGES before FPN feature extraction
  # The detection model requires properly preprocessed images to generate quality FPN features
  transforms:
    resize:
      enabled: true
      size: [384, 1280]      # Resize to standard detection input size
    
    crop:
      enabled: false         # No cropping for detection
      size: 256
    
    flip:
      enabled: false         # No data augmentation for feature extraction
      probability: 0.5
    
    color_jitter:
      enabled: false         # No color augmentation for feature extraction
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    
    normalize:
      enabled: true          # Essential for pretrained detection model
      mean: [0.485, 0.456, 0.406]  # ImageNet normalization
      std: [0.229, 0.224, 0.225]
  
  # Same preprocessing for validation (no augmentation needed)
  test_transforms:
    resize:
      enabled: true
      size: [384, 1280]      # Same size for consistency
    
    crop:
      enabled: false         # No cropping for detection
      size: 256
    
    flip:
      enabled: false         # No augmentation for validation
      probability: 0.5
    
    color_jitter:
      enabled: false         # No augmentation for validation
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    
    normalize:
      enabled: true          # Essential for pretrained detection model
      mean: [0.485, 0.456, 0.406]  # ImageNet normalization
      std: [0.229, 0.224, 0.225]

training:
  # Training parameters
  batch_size: 4            # Smaller batch size due to larger feature maps
  epochs: 100
  learning_rate: 1e-5     # Lower learning rate for feature compression
  lambda: 1e-3            # Rate-distortion trade-off parameter
  log_interval: 10
  
  # Optimizer settings
  optimizer:
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 1e-4
  
  # Learning rate schedule
  lr_schedule:
    enabled: true
    factor: 0.8
    patience: 5
    min_lr: 1e-6
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 15
    min_delta: 1e-6
  
  # Training output
  save_dir: 'checkpoints/fpn_compression'
  num_workers: 4  # Safe since we'll extract FPN features in training loop, not in DataLoader

validation:
  interval: 5              # Validation every N epochs
  save_reconstructions: true
  num_samples: 4           # Number of samples to analyze

# Experiment settings
experiment:
  name: 'fpn_feature_compression_v2'
  description: 'Training factorized prior model for FPN feature compression with proper lambda scaling' 